### PR TITLE
add -js option to execute custom JavaScript code after page load

### PR DESCRIPTION
**Pull request by vszakats**
* also bump some URLs to HTTPS

### CODE REVIEW

**Comment by vszakats** [comment]
Any comment on this? The patch is tested working and it's useful for example to save pages where certain elements need clicking to become visible.

**Comment by newzealandpaul** [comment]
Thanks for the pull request. I am merging it in. I will give you credit in the README.

**Comment by vszakats** [comment]
@newzealandpaul: Thank you!

New release now merged to Homebrew: https://github.com/Homebrew/homebrew-core/commit/62891656ed64f7d38a2a174c4a353a764ee590b2

**Comment by newzealandpaul** [comment]
Fantastic thank you. I have updated the README to include HomeBrew install instructions and gave you credit for sorting out homebrew. Thanks mate.

**Pull request merged**
